# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
np.random.random((3,3,3))

array([[[0.18959299, 0.75788601, 0.05019714],
        [0.37456819, 0.190115  , 0.58352723],
        [0.33854603, 0.02392963, 0.9759976 ]],

       [[0.16474672, 0.96154518, 0.22629001],
        [0.37128854, 0.66899953, 0.74187744],
        [0.14423583, 0.34781634, 0.94529512]],

       [[0.7573784 , 0.25271428, 0.34394905],
        [0.12608432, 0.09137187, 0.60016455],
        [0.74372377, 0.4404343 , 0.41784642]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
arr=np.diag([1,2,3,4], -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
arr=np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [4]:
arr = np.random.random((5,5))
armax, armin = arr.max(), arr.min()
arr = (arr - armin)/(armax - armin)
print(arr)

[[0.36648683 0.27880938 0.85177538 0.94453992 1.        ]
 [0.         0.29389461 0.48267674 0.11862264 0.44513003]
 [0.81130672 0.56059538 0.56754744 0.22010119 0.47405522]
 [0.91877722 0.40664251 0.54519506 0.40910995 0.80265524]
 [0.56377324 0.15299205 0.72533173 0.03714005 0.33185563]]


# 5. How to find common values between two arrays?

In [6]:
ar1 = np.random.randint(0,15,15)
print("Array1:",ar1)
ar2 = np.random.randint(0,15,15)
print("Array2:",ar2)
print(np.intersect1d(ar1,ar2))

Array1: [11  1 14  3 14 11 12  0  6  2  2  6  2  9  7]
Array2: [ 6  5 12  9  5 13  9  4 13 14  0  4  0  3 11]
[ 0  3  6  9 11 12 14]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)
print(yesterday,today,tomorrow)

2020-08-22 2020-08-23 2020-08-24


# 7. Consider two random array A and B, check if they are equal

In [9]:
ar1 = np.random.randint(0,15,15)
ar2 = np.random.randint(0,15,15)
print("Array1:",ar1)
print("Array2:",ar2)
equal = np.allclose(ar1,ar2)
equal

Array1: [ 6 12  6  4  6  3  3 10 13  8 14  7  1  4  0]
Array2: [ 3  2  6  0 10  5  0 13  0  4  5  3  4  0  1]


False

# 8.Create random vector of size 10 and replace the maximum value by 0

In [10]:
v = np.random.random((10))
v[v.argmax()] = 0
v

array([0.80894945, 0.30995702, 0.4806604 , 0.73469294, 0.        ,
       0.73897212, 0.46932   , 0.71782111, 0.18521087, 0.0217258 ])

# 9. How to print all the values of an array?

In [11]:
np.random.random((5,5))

array([[0.61075236, 0.72925992, 0.86388523, 0.0060173 , 0.88069999],
       [0.71466223, 0.34447443, 0.0442689 , 0.26162074, 0.39696162],
       [0.6297415 , 0.6140662 , 0.10941286, 0.27142673, 0.43180663],
       [0.41944691, 0.07877004, 0.28405295, 0.28852377, 0.77328444],
       [0.15532664, 0.87421553, 0.41997102, 0.38013934, 0.06918063]])

# 10.Subtract the mean of each row of a matrix

In [12]:
ar = np.random.random((5,5))
output = ar-ar.mean()
print(output)

[[-0.44455804 -0.26243679 -0.07832709  0.0732521   0.1890166 ]
 [-0.13453772 -0.1730567  -0.495416    0.39729417  0.365337  ]
 [ 0.09633898 -0.28813768  0.03778717  0.02702652 -0.29209947]
 [ 0.484923    0.35767094  0.13718663 -0.36578526 -0.21792986]
 [ 0.24970668  0.3066311   0.11055581  0.02168335 -0.10212543]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [14]:
v = np.random.randint(1,10,10)
print("Given vector:", v)
b = np.random.randint(v)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    v[j] += 1

print("Indexing vector:", b)
print("Result:",v)

Given vector: [2 3 2 6 2 5 7 5 4 9]
Indexing vector: [0 0 0 0 1 1 1 3 4 5]
Result: [3 4 2 7 3 6 7 5 4 9]


# 12.How to get the diagonal of a dot product?"

In [15]:
A = np.random.random((5,5))
B = np.random.random((5,5))
np.diag(np.dot(A, B))

array([1.36536418, 1.3459638 , 1.31411346, 1.86860273, 1.41270186])

# 13.How to find the most frequent value in an array?

In [17]:
z = np.random.randint(0,50,20)
print(np.bincount(z).argmax())

6


# 14.How to get the n largest values of an array

In [18]:
Z = np.arange(10000)
n = 10
print (Z[np.argsort(Z)[-n:]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [27]:
arr1=np.array(['Animals','Dog','Cat','Rat','Tiger'])
arr2=np.array(['color','Red','Green','Orange','Yellow'])
result= np.core.records.fromarrays([arr1, arr2])
for i in range(5):
    print(result[i])

('Animals', 'color')
('Dog', 'Red')
('Cat', 'Green')
('Rat', 'Orange')
('Tiger', 'Yellow')
